apiVersion: v1
kind: Pod
metadata:
  name: kube-mnist1
spec:
  containers:
  - name: tf-mnist-1gpu
    image: centaurusinfra/tf-onegpu-mnist:latest
    workingDir: /tmp/test
    command: ["sh", "-c", "python3 mnist.py"]
  restartPolicy: OnFailure
