apiVersion: kubeshare.nthu/v1
kind: SharePod
metadata:
  name: localtf
  annotations:
    "kubeshare/gpu_request": "0.4"
    "kubeshare/gpu_limit": "0.8"
    "kubeshare/gpu_mem": "3145728000"
    "kubeshare/sched_affinity": "red" # optional
    "kubeshare/sched_anti-affinity": "green" # optional
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: centaurusinfra
    image: centaurusinfra/tensorflow:nightly-gpu-jupyter-tfds-profiler
    # resources:
    #   limits:
    #     memory: "4Gi"
    workingDir: /root/test
    command: ["sh", "-c", "python3 mnist.py"]
    volumeMounts:
      - name: bin
        mountPath: /root/test
  volumes:
    - name: bin
      hostPath:
         path: /home/steven/dev/tf_experiments
  restartPolicy: OnFailure
