apiVersion: kubeshare.nthu/v1
kind: SharePod
metadata:
  name: cfresnet50-1
  annotations:
    "kubeshare/gpu_request": "0.4"
    "kubeshare/gpu_limit": "1.0"
    "kubeshare/gpu_mem": "3145728000"
    "kubeshare/sched_affinity": "red" # optional
    "kubeshare/sched_anti-affinity": "blue" # optional
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: centaurusinfra
    image: centaurusinfra/tensorflow:nightly-gpu-jupyter-tfds-profiler
    workingDir: /root/test
    command: ["sh", "-c", "cd /root/test; python tf-cf-rn50-pack.py"]
    volumeMounts:
      - name: bin
        mountPath: /root/test
  volumes:
    - name: bin
      hostPath:
         path: /nfs_3/tf_records/ml_tests/kubeshare
  restartPolicy: OnFailure
