apiVersion: kubeshare.nthu/v1
kind: SharePod
metadata:
  name: localmnist
  annotations:
    "kubeshare/gpu_request": "0.4"
    "kubeshare/gpu_limit": "0.6"
    "kubeshare/gpu_mem": "3145728000"
    "kubeshare/sched_affinity": "red" # optional
    "kubeshare/sched_anti-affinity": "green" # optional
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: onegpu
    image: centaurusinfra/tf-onegpu-mnist:latest
    workingDir: /tmp/test
    command: ["sh", "-c", "python3 mnist.py"]
  restartPolicy: OnFailure

