apiVersion: kubeshare.nthu/v1
kind: SharePod
metadata:
  name: localmnist2
  annotations:
    "kubeshare/gpu_request": "0.3"
    "kubeshare/gpu_limit": "0.5"
    "kubeshare/gpu_mem": "2145728000"
    "kubeshare/sched_affinity": "red" # optional
    "kubeshare/sched_anti-affinity": "yellow" # optional
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: onegpu
    image: centaurusinfra/tf-onegpu-mnist:latest
    workingDir: /tmp/test
    command: ["sh", "-c", "python3 mnist.py"]
  restartPolicy: OnFailure
