apiVersion: kubeshare.nthu/v1
kind: SharePod
metadata:
  name: localsh
  annotations:
    "kubeshare/gpu_request": "0.4"
    "kubeshare/gpu_limit": "1.0"
    "kubeshare/gpu_mem": "3145728000"
    "kubeshare/sched_affinity": "red" # optional
    "kubeshare/sched_anti-affinity": "green" # optional
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: centaurusinfra
    image: centaurusinfra/tensorflow:nightly-gpu-jupyter-tfds-profiler
    workingDir: /root/test
    command: ["sh", "-c", "jupyter notebook --no-browser --ip 0.0.0.0 --port=8888 --allow-root"]
    volumeMounts:
      - name: bin
        mountPath: /root/test
  volumes:
    - name: bin
      hostPath:
         path: /home/steven/dev/tf_experiments
  restartPolicy: OnFailure
