apiVersion: kubeshare.nthu/v1
kind: SharePod
metadata:
  name: tfmnist
  annotations:
    "kubeshare/gpu_request": "1.0"
    "kubeshare/gpu_limit": "1.0"
    "kubeshare/gpu_mem": "3145728000"
    "kubeshare/sched_affinity": "red" # optional
    "kubeshare/sched_anti-affinity": "green" # optional
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: centaurusinfra
    image: tensorflow/tensorflow:2.7.1-gpu
    workingDir: /root/test
    command: ["sh", "-c", "cd /root/test; python tfmnist.py; sleep infinity"]
    volumeMounts:
      - name: bin
        mountPath: /root/test
  volumes:
    - name: bin
      hostPath:
         path: /nfs_3/tf_records/ml_tests/kubeshare
  restartPolicy: OnFailure
